[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700
chown=root:root

[supervisord]
user=root
logfile=${LOG_DIR}supervisord.log
loglevel=debug
pidfile=/var/run/supervisord.pid
childlogdir=${LOG_DIR}
nodaemon=true
logfile_maxbytes=50MB
logfile_backups=10
umask=002
directory=/

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock
chmod=0700

##############################################
#-port <порт>: Номер сетевого порта главного менеджера кластера. По умолчанию — 1541. Если не указан, используется значение по умолчанию.
# 🟡 rmngr — менеджер кластера
#[program:rmngr]
#command=${PATH_TO_1C}/rmngr -d ${DATA} -port 1541 -regport 1541 -range ${ONEC_PORT_RANGE} -debug
#user=root
#autostart=true
#autorestart=true
#startsecs=64 
#priority=10   # 🟢 Ставим первым
#startretries=0
#stdout_logfile=${LOG_DIR}rmngr.out.log
#stderr_logfile=${LOG_DIR}rmngr.err.log

##############################################
# 🔁 ragent — агент сервера
[program:ragent]
command=${BIN}/start-ragent.sh
user=root
autostart=true
autorestart=false
startsecs=2
startretries=3
priority=20   # 🟢 Ставим вторым
stdout_logfile=${LOG_DIR}ragent.out.log
stderr_logfile=${LOG_DIR}ragent.err.log
environment=HOME="/home/onec",XDG_CACHE_HOME="/home/onec/.cache"


##############################################
# 🔁 ras — служба администрирования (ждёт rmngr)
[program:ras]
command=${BIN}/start-ras.sh
user=root
autostart=true
autorestart=false
startsecs=10
startretries=3
priority=20
stopwaitsecs=15
stopsignal=TERM
stdout_logfile=${LOG_DIR}ras.out.log
stderr_logfile=${LOG_DIR}ras.err.log


##############################################
# 🟡 rphost — рабочие процессы
[program:rphost]
command=${PATH_TO_1C}/rphost -regport 1541 -d ${DATA}
user=root
autostart=false
autorestart=false
startsecs=5
startretries=3
stdout_logfile=${LOG_DIR}rphost.out.log
stderr_logfile=${LOG_DIR}rphost.err.log

##############################################
# ⚙️ init-cluster
[program:init-cluster]
command=${BIN}/init-cluster.sh
user=root
autostart=true
autorestart=false
exitcodes=0
startsecs=0
priority=90
stdout_logfile=${LOG_DIR}init-cluster.out.log
stderr_logfile=${LOG_DIR}init-cluster.err.log

##############################################
# ⚙️ init-server
[program:init-server]
command=${BIN}/init-server.sh
user=root
autostart=true
autorestart=false
startsecs=0
priority=190
stdout_logfile=${LOG_DIR}init-server.out.log
stderr_logfile=${LOG_DIR}init-server.err.log

##############################################
# ⚙️ init-ib
[program:init-ib]
command=${BIN}/init-ib.sh
user=root
autostart=true
autorestart=false
startsecs=0
priority=290
stdout_logfile=${LOG_DIR}init-ib.out.log
stderr_logfile=${LOG_DIR}init-ib.err.log

 
[program:init-web]
command=${BIN}/init-web.sh
user=root 
autostart=true
autorestart=false
startsecs=0
priority=390
stdout_logfile=${LOG_DIR}init-web.out.log
stderr_logfile=${LOG_DIR}init-web.err.log

[program:apache2]
command=/usr/sbin/apachectl -D FOREGROUND
user=root
stopwaitsecs=10
stopsignal=TERM
autostart=true
autorestart=true
stderr_logfile=/var/log/apache2/apache2.err.log
stdout_logfile=/var/log/apache2/apache2.out.log


[program:xrdp]
command=/usr/sbin/xrdp -nodaemon
autostart=true
autorestart=true
stdout_logfile=${LOG_DIR}xrdp.out.log
stderr_logfile=${LOG_DIR}xrdp.err.log

[program:xrdp-sesman]
command=/usr/sbin/xrdp-sesman --nodaemon
autostart=true
autorestart=true
stdout_logfile=${LOG_DIR}sesman.out.log
stderr_logfile=${LOG_DIR}sesman.err.log 


 
